name: candrive_mobile
description: App mobile per visualizzare i messaggi CAN da smartphone

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  socket_io_client: ^2.0.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  intl: ^0.17.0
  flutter_svg: ^1.0.3
  fl_chart: ^0.50.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/